[package]
name = "bio_seq"
version = "0.1.0"
edition = "2024"

[lib]
name = "bio_seq"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module"] }
bio-seq = "0.14"
